# Generated by Django 2.0.7 on 2018-11-05 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movers',
            options={'verbose_name_plural': 'Movers'},
        ),
        migrations.AddField(
            model_name='movers',
            name='services',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
