# Generated by Django 2.0.7 on 2018-11-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_movers_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movers',
            name='location',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movers',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
