# Generated by Django 2.0.7 on 2018-11-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0005_delete_movers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Mover',
            },
        ),
    ]
