# Generated by Django 2.0.7 on 2018-11-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_mover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mover',
            new_name='Movers',
        ),
        migrations.AlterModelOptions(
            name='movers',
            options={'verbose_name_plural': 'Movers'},
        ),
    ]
