# Generated by Django 2.0.7 on 2018-11-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20181105_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movers',
        ),
    ]
