# Generated by Django 2.0.7 on 2018-11-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_movers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movers',
            name='location',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='movers',
            name='name',
            field=models.CharField(max_length=1),
        ),
    ]
