# Generated by Django 2.0.7 on 2018-11-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20181105_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movers',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='movers',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
