# Generated by Django 2.0.7 on 2018-11-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20181021_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counties',
            options={'verbose_name_plural': 'Counties'},
        ),
    ]
